### ISSUE TITLE
Feature request: M3U support

### ISSUE THREAD

**Issue by superandroidtron** [droidmjt/Droidsound#135]
I love Droidsound, but I really wish it had M3U support. I have a lot of VGM format music and I'd like to be able to use the playlists from Project 2612.

**Comment by droidmjt** [comment]
Recenty I was trying to implement this feature and i thought, is this even needed? If you take a zip from project 2612 and drop it to /mnt/sdcard/DSEMusic and rescan the folder, there will be a new archive container and if you enter to it and select any song file, it will automatically create an internal playlist that contains all the songs and their infos. Then you can click prev/next to go through the songs. 

The only difference between the above and the feature request would be that after clicking the .m3u file, the exactly same content you would see inside an archive container, you would also see in PLAYLISTS tab under a new item.  What would be the point having the same content in two different place?

It would be annoying instead of useful in my opinion :) 

My apologies for this, I've been busy in real life and didn't have time earlier to check this out. One other reason is that there is just 1 developer for this project.
