### ISSUE TITLE
vgmstream updated to r1050

### ISSUE THREAD

**Issue by 47iscool** [droidmjt/Droidsound#215]
https://gitlab.kode54.net/kode54/vgmstream/commits/master

**Comment by kode54** [comment]
I try to keep my Github repository in sync with my personal Gitlab, but the Gitlab site is my primary host for all repositories.

**Comment by 47iscool** [comment]
Was just letting the maintainer of DSE know in case he didn't.

**Comment by kode54** [comment]
Thanks so much for doing that, it didn't occur to me to keep people up to date on these things. I take for granted that people can try to get into my site, which is a bit of a pain. Without an account, you can only use the Explore link to view a page that needs to be reconfigured to view the list of projects. (The default view, popular projects, shows nothing, because not enough people have starred anything on my site.)

**Comment by droidmjt** [comment]
Thanks for the infos.
