### ISSUE TITLE
mp3's freezing phone while screen is locked at random (again)

### ISSUE THREAD

**Issue by GL1TCH04** [droidmjt/Droidsound#224]
i'm currently running another S6 port (i always had trouble deciding which rom to use, don't ask)

the locking up is back, but it seems like the chance is now a lot lower
only happens while the screen is off and only after about 2 or 3 minutes of playback

phone: i9505 (galaxy s4 lte)
rom: WizCyan S6 port
droidsound version: 1.6647_09

**Comment by droidmjt** [comment]
can you see the case here? :) when ever you put the S6 port back, problems arrive, how i suppose to fix it? I have no device where i could reproduce the problem.

**Comment by GL1TCH04** [comment]
yes, i know, but i had this issue on the last S6 port and one of the test builds you sent me fixed it completely

**Comment by droidmjt** [comment]
now i remember, its the BASS/FFmpeg thing, BASS library is not tested with your ROM and fails probably because of that but FFmpeg worked. A workaround for this would be to make FFmpeg play the same formats. I can get this fixed so that user can decide which lib to use for modern formats. But don't expect it to be ready any time soon.

**Comment by GL1TCH04** [comment]
that's perfectly fine
the bigger issue (that i forgot to put into the title) is, that it actually now also seems to be happening with other formats
it happened once while i was playing an atari 2600 song (.sap)

**Comment by droidmjt** [comment]
Unfortunately that (.sap thing) I can't fix.

**Comment by GL1TCH04** [comment]
ah that's a shame
i guess i'll just wait out the coming updates and see

if it won't stop acting weird, i guess i'll have to switch over to XMP and modo

**Comment by droidmjt** [comment]
heh, now tell me, how could I possibly fix something that I cannot reproduce? without seeing these problems, I would end up blindly trying something that could never be fixed in the worst case. If FFmpeg fixed the phone freezing problem then it means its library related problem, for SAP, there are just couple of libraries (both included in DSE), modo is using the same library for SAP as DSE so logically thinking the same locking should happen with modo also. Whether it happens or not, it doesn't matter since it won't produce crashlog so we are back in the main problem. 

Try to see this from developer point of view, what would you do?

**Comment by GL1TCH04** [comment]
well i'd obviously be confused
