### ISSUE TITLE
Folder browser crashes with folders with ".zip" and related extensions

### ISSUE THREAD

**Issue by jimbo1qaz** [droidmjt/Droidsound#325]
I'm using the Folder Browser to load songs.

When I open a folder named "folder.zip", "folder.zip.f", "folder.f.zip", et cetera, the folder browser crashes.

The "extension" can be followed by more extensions, and still cause the crash.

```
08-26 00:24:41.582 11891-11891/com.droidmjt.droidsounde D/Droidsound: PlayListAdapter: FILENAME f.zip.f
08-26 00:24:41.583 11891-11891/com.droidmjt.droidsounde D/Droidsound: PlayerActivity: Clicked /storage/emulated/0/droidsound/dsroot/Music.fsb_source/smwc -> /storage/emulated/0/droidsound/dsroot/Music.fsb_source/smwc/f.zip.f
08-26 00:24:41.584 11891-11891/com.droidmjt.droidsounde D/Droidsound: SongDatabase: files in path '/storage/emulated/0/droidsound/dsroot/Music.fsb_source/smwc/f.zip.f'
                                                                      
                                                                      --------- beginning of crash
```

**Comment by droidmjt** [comment]
great, i fix it at some point

**Comment by Galindorf** [comment]
Holy CATS this has been annoying. I had Droidsound, then Droidsound-E, and I decided to update to the latest version of Droidsound-E. Well the first thing it did was rescan the database. I could not stop it; and it would crash my program before I could use it. Over and over again. I cleared the data, uninstalled, went through my files with the "My Files" file browsers and deleted my entire music collection, as well as the Droidsound folder, the dsroot folder, and also the DSEM music folder. 
It STILL tried to scan the database, turns out you can't just delete some folders, it took me FOUR tries between deleting caches/uninstalling/clearing data/restarting and using Android File Transfer on mac to get rid of these folders, once I finally figured out where they were. I'm about to try again, without any of my PSX music because it's all zip files. I LOVE this program, I use it for all my music, not just the chiptunes.

**Comment by jimbo1qaz** [comment]
@Galindorf - This is a bug I found where the filesystem browser crashes when navigating to a .zip folder. If it crashes on rescanning a folder, you're using a DB browser, which is NOT the same as the filesystem browser, and is UNAFFECTED by the .zip crash.

I suggest you quit DSE. Then rename your `/sdcard/dsroot` folder (you can leave DSEMusic intact), clear app data. Then install the latest APK (search issues for 99.apk or here: https://www.dropbox.com/s/ydjghw2m85u6o4x/droidsounde16647_99.apk?dl=1). Does it work afterwards?

You should start your own issue.

**Comment by Galindorf** [comment]
ooooohhh, got it. I did manage to fix my issue after completely deleting everything and then re-adding the files a little at a time. I even got it to scan the database with the zipped files in them, and play them. As it was, the database scan would go fine until it hit the .zip and .7z files of the PSX music and then crash. I forgot to add that part. It would crash when scanning the zip files, which is why I added my issue here. Sorry about that!

**Comment by droidmjt** [comment]
get the latest build from frontpage

**Comment by jimbo1qaz** [comment]
...so this just happened... (Avast on Android)
![tmp_20497-screenshot_20160906-220034-161597287](https://cloud.githubusercontent.com/assets/913957/18300363/72a07cbe-747d-11e6-914c-79b63eb41e8d.png)

**Comment by droidmjt** [comment]
https://www.virustotal.com/en/file/8f61950ff6f77d64b6aee4f9166e305cad2c99577e991aba76dce97a8e1f02b0/analysis/1473228061/

The only reason why they might think it is dangerous is because of few permissions, thats all.
