### ISSUE TITLE
Faster (less power consumption) SNES SPC core?

### ISSUE THREAD

**Issue by jimbo1qaz** [droidmjt/Droidsound#331]
The current SPC core in GEP is cycle-accurate and rather power-hungry on phones. Do you want to add a lighter SPC library?

(possible example: https://github.com/yupferris/snes_spc/blob/master/readme.txt)

**Comment by droidmjt** [comment]
thanks but I pass it for now

**Comment by TeamFail** [comment]
Hate to bump up a closed issue, but my phone (Samsung S5 Neo) is having a very hard time with SPCs in specific - every other audio format seems to work fine, including RSP N64 playback, but any and all SPCs seem to stutter a lot whenever the screen is off for any amount of time. I recently had to wipe and reset my phone since I accidentally FRP locked it, so I was able to try it on a system that was pretty much borderline stock with very few background apps and it was still very stuttery when the screen was off. With it on, it worked fine, but even with a full wakelock set, the plugin is still not completely reliable because of the amount of processing power it requires.

**Comment by droidmjt** [comment]
I just tested the latest build with 1.2GHz Android 4.2 phone and even with Sinc interpolation and screen turned off it worked fine, but it do stutter on more powerful phone using Android 6.0.1. I noticed similar problem earlier with C64 SIDs. This doesn't happen on CM13 (SGS3).

**Comment by TeamFail** [comment]
Yeah, I'm running 6.0.1 as well, perhaps it's an issue with Marshmallow itself. I wonder if it's also happening on Nougat.

**Comment by theGIZOID** [comment]
Funnily enough I don't have any of these problems on my Samsung Galaxy S4, using Android 6.0.1. You might want to use a different CPU governor, that might fix your stuttering problem with spc files.

**Comment by TeamFail** [comment]
Unfortunately I only have an interactive governor in my kernel and nothing else, so that's not an option for me.
