### ISSUE TITLE
Google Assistant compatibility request

### ISSUE THREAD

**Issue by 1983parrothead** [droidmjt/Droidsound#458]
Hello there. Thank you for creating and updating droidsound app series including the Enhanced "e" versions.

I would like to know if it can be updated to Google Assistant compatibility? If so, is it any good idea?

Thank you ^^

**Comment by droidmjt** [comment]
What would be the benefit of having Google Assistant compatibility in Droidsound-E ?

**Comment by 1983parrothead** [comment]
I guess that is too complicated right now🤔

Simply asking it to play an album or at least a playlist might be okay. It's up to you. I'd rather follow your preferences😊

**Comment by theGIZOID** [comment]
I could name one scenario where this could be useful: Driving a car. I use my phones headphone jack to connect it to the radio and listen to my music that way. With the google assistant I could just simply tell it to skip ahead to the next song or song XYZ without having to touch anything and staying focused on the road. With that said I myself wouldn't benefit too much from it because I usually just listen through full albums and/or playlists without skipping, but for someone who wants to change their music while driving this could be a useful feature.

**Comment by droidmjt** [comment]
sounds like a BS feature for now, sorry, no go
