### ISSUE TITLE
Read file is so slow on Android 11

### ISSUE THREAD

**Issue by Yave-Yu** [droidmjt/Droidsound#609]
I updated to Android 11 recently, then Droidsound-E is so slow on reading file, including choose multi-song such as nsf.

**Comment by droidmjt** [comment]
Tested with emulator and worked normally. I don't have a real device with Android 11 so I cannot test this further. I'll get back to this once I have Android 11 device.

**Comment by droidmjt** [comment]
see issue #612, it might solve this problem also

**Comment by Sci3ntia** [comment]
I have this issue too, due to android 11's scoped storage, reading folders with more than 100 small files (txtp, 2sf, etc) is extremely slow, I would encourage you to try with 100+ small files in an emulator and see how folder loading fares. I have no clue if this can be worked around or if android 11 will just be very slow
