### ISSUE TITLE
Bad performance on Samsung Galaxy A52 5G (Android 11), gives "made for an older version of Android" performance notice.

### ISSUE THREAD

**Issue by stgiga** [droidmjt/Droidsound#633]
My Samsung Galaxy A52 5G on Android 11 has significantly worse performance in Droidsound-E than my Galaxy S8 on Android 9. The A52 has both UI issues and playback issues. In fact, the UI issues can even crash the app in a loop. Also stuff like NSFplay, VGMplay, and BassMIDI have severe handicaps compared to my S8. In fact, BassMIDI can't even handle my Jummbox soundfont on songs it previously could, a bank so simple in construction that it should have no issues. When I load the app it gives the warning about not made for current Android, including the performance part of the warning. I'm using the newest x64 version.

**Comment by droidmjt** [comment]
If the latest version works perfectly on S8 but not with A52, all I can say is, make sure you have the latest firmware in your phone. I've read that some older Android 11 versions had performance issues due to filesystem change. I have Android 11 with April 2021 patch and everything works as before.
